all:
	@echo Nothing to be made.

clean:
	@echo Nothing to be made.

install:
	install -D hostapd.conf $(DESTDIR)/etc/hostapd/hostapd.conf
	install -D init $(DESTDIR)/etc/init.d/hostapd
	install -D default $(DESTDIR)/etc/default/hostapd
